### ISSUE TITLE
Pathcer (from 1809).bat location

### ISSUE THREAD

**Issue by fyarl** [MineSweeper73/1000Hz-Polling-Hack-1809#3]
Pathcer (from 1809).bat is missing.

**Comment by MineSweeper73** [comment]
You are in the wrong repo if u want to use 1903. But if u are on 1809, u don't need it. I corrected my README. sorry for the confusion.

**Comment by MineSweeper73** [comment]
1000Hz-Polling-Hack-1903 this is the one u want
